/*************** AUTOGENERATED @ 1274493067350 ***************
    WARNING: THIS FILE WAS AUTOGENERATED BY THE FORMAT BUILD SCRIPT
    MODIFYING THIS FILE IS FINE, BUT YOU REALLY SHOULD BE MODIFYING 
    THE LIBRARY DIRECTLY AND REGENERATING THIS FILE USING BUILD.js!!!!
    format.js - Written by Marak Squires
 
*/
var format = {};
format.version = "0.0.1";
format.types = {};
format.types.isDefined = function ( objecty ){
  if(typeof objecty == 'undefined'){
    return false;
  }
  if(objecty == null || objecty == 'null'){
    return false;
  }
  if(objecty.toString() == 'NaN'){
    return false;  
  }
};

format.types.isType = function (){
  
};

format.types.isNumber = function ( numbery ){
  if(numbery.toString() == 'NaN'){
    return false;  
  }
  if(numbery instanceof Number){
    return true; 
  }
  else{
    return false;
  }
};

format.types.isString = function ( stringy ){
  return (stringy instanceof String);
};

format.types.isText = function ( texty ){

};

format.types.isDate = function ( datey ){
  return (datey instanceof Date);
};

format.types.isTime = function ( timey ){
  
};

format.types.isArray = function (){
  
};

format.types.isInflector = function (){
  
};

format.types.isJSON = function (){
  
};

format.types.isAssociativeArray = function (){
  
};

format.inflector = {};
format.inflector.camelize = function (str) {
  return exports.titleize(str).replace(/[^\w]/, '');
};

format.inflector.classify = function () {};

format.inflector.constantize = function (str) {
  return eval(str); //this is evil and prevents chaining
};

format.inflector.dasherize = function (str) {
  str = str.replace(/_/g, '-');
  return str;
};

format.inflector.demodulize = function () {};

format.inflector.foreign_key = function () {};

format.inflector.humanize = function (str) {
  str = str.replace(/_id$/, "").replace(/_/, " ");
  return str.charAt(0).toUpperCase() + str.slice(1);
};

format.inflector.ordinalize = function () {};

format.inflector.tableize = function () {};

format.inflector.titleize = function (str) {

  str = exports.underscore(str);
  str = exports.humanize(str);
  
	var parts = str.split(/\b('?[a-z])/);
	str = '';

	for (var i = 0; i < parts.length; i = i + 1) {
		if ((i % 2) === 0) {
			str = str + parts[i];
		} else {
			str = str + parts[i].charAt(0).toUpperCase() + parts[i].slice(1);
		}
	};

	return str;
};

format.inflector.underscore = function (str) {
	str = str.replace(/::/g, '/').replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2');
	str = str.replace(/([a-z\d])([A-Z])/g, '$1_$2').replace(/-/g, "_");
	str = str.toLowerCase();
	return str;
};

format.inflector.pluralize = function (str) {
	for (var i = inflections.uncountables.length - 1; i >= 0; i--) {
		if (str.match(inflections.uncountables[i])) return str;
	};

	var pairs = inflections.plurals,
		pair = [];

	//go from the end of the array to the front so the last pairs have priority
	for (i = pairs.length - 1; i >= 0; i--) {
		pair = pairs[i];
		var result = str.replace(pair[0], pair[1]);
		if (result === str) {
			continue;
		} else return result;
	};

	return str.replace(/([^s])$/i, '$1s');
};

format.inflector.singularize = function (str) {
	for (var u = inflections.uncountables.length - 1; u >= 0; u--) {
		if (str.match(inflections.uncountables[u])) return str;
	};

	var pairs = inflections.singulars,
		pair = [];

	//go from the end of the array to the front so the last pairs have priority
	for (var i = pairs.length - 1; i >= 0; i--) {
		pair = pairs[i];
		var result = str.replace(pair[0], pair[1]);
		if (result === str) {
			continue;
		} else return result;
	};

	return str.replace(/s$/i, '');
};

format.number = {};
format.number.toNumber = function (numbery){
  
  var n = numbery;
  n = n.toString();
  n = n.replace( /\,/g, '' );
  n = n.replace( /\$/g, '' ); // replace with format.currency.toCurrency call
  n =  new Number(n);

  if(n.toString() == 'NaN'){
    return false;
  }
  else{
    return n;
    
  }
};

format.number.toExponential = function (){};

format.number.toFixed = function (){};

format.number.toPercent = function (number){
  // TODO: add more stripping and formatting logic
  return number;
};

format.number.toBase = function ( number ){
  
  Number.prototype.toBase = function(b, c){
      var s = "", n = this;
      if(b > (c = (c || "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz").split("")).length || b < 2) return "";
      while(n)
          s = c[n % b] + s, n = Math.floor(n / b);
      return s;
  };
  String.prototype.parseInt = function(b, c){
      var s = 0, n, l = (n = this.split("")).length, i = 0;
      if(b > (c = c || "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz").length || b < 2) return NaN;
      while(l--)
          s += c.indexOf(n[i++]) * Math.pow(b, l);
      return s;
  };
  
};

format.string = {};
format.string.stripNumbers = function ( str ){
  return str.replace(/[^A-Za-z]/g, "");
};

format.string.getNumbers = function ( str ){
  return str.replace(/[^\d]/g, "");
};

format.string.stripLetters = function ( str ){
  return;
};

format.string.getLetters = function ( str ){
  
};

format.string.wordWrap = function ( m, b, c ){
  
      var i, j, l, s, r;
      if(m < 1)
          return this;
      for(i = -1, l = (r = this.split("\n")).length; ++i < l; r[i] += s)
          for(s = r[i], r[i] = ""; s.length > m; r[i] += s.slice(0, j) + ((s = s.slice(j)).length ? b : ""))
              j = c == 2 || (j = s.slice(0, m + 1).match(/\S*(\s)?$/))[1] ? m : j.input.length - j[0].length
              || c == 1 && m || j.input.length + (j = s.slice(m).match(/^\S*/)).input.length;
      return r.join("\n");
  
};

format.string.trim = function ( str ){
  return str;
};

format.string.left = function ( str, n ){
  return str;
};

format.string.right = function ( str, n ){
  return str;
};

format.string.toQueryParams = function ( str ){
  return str;
};

format.date = {};
format.date.toDate = function (datey){
  // TODO: add more stripping and formatting logic
  return timey;
};

format.date.toTime = function (timey){
  // TODO: add more stripping and formatting logic
  return timey;
};

format.date.toSeconds = function (timey){
    // TODO: add more stripping and formatting logic
    return timey;
  };

format.date.toMinutes = function (timey){
    // TODO: add more stripping and formatting logic
    return timey;
  };

format.date.toHours = function (timey){
    // TODO: add more stripping and formatting logic
    return timey;
  };

format.date.toDays = function (timey){
    // TODO: add more stripping and formatting logic
    return timey;
  };

format.date.toMonths = function (timey){
    // TODO: add more stripping and formatting logic
    return timey;
  };

format.date.toYears = function (timey){
    // TODO: add more stripping and formatting logic
    return timey;
  };

format.date.TimeSpan = function (days,hours,minutes,seconds,milliseconds){this.days=0;this.hours=0;this.minutes=0;this.seconds=0;this.milliseconds=0;if(arguments.length==5){this.days=days;this.hours=hours;this.minutes=minutes;this.seconds=seconds;this.milliseconds=milliseconds;}
  else if(arguments.length==1&&typeof days=="number"){var orient=(days<0)?-1:+1;this.milliseconds=Math.abs(days);this.days=Math.floor(this.milliseconds/(24*60*60*1000))*orient;this.milliseconds=this.milliseconds%(24*60*60*1000);this.hours=Math.floor(this.milliseconds/(60*60*1000))*orient;this.milliseconds=this.milliseconds%(60*60*1000);this.minutes=Math.floor(this.milliseconds/(60*1000))*orient;this.milliseconds=this.milliseconds%(60*1000);this.seconds=Math.floor(this.milliseconds/1000)*orient;this.milliseconds=this.milliseconds%1000;this.milliseconds=this.milliseconds*orient;return this;}
  else{return null;}};

format.date.compare = function (timeSpan){var t1=new Date(1970,1,1,this.hours(),this.minutes(),this.seconds()),t2;if(timeSpan===null){t2=new Date(1970,1,1,0,0,0);}
  else{t2=new Date(1970,1,1,timeSpan.hours(),timeSpan.minutes(),timeSpan.seconds());}
  return(t1>t2)?1:(t1<t2)?-1:0;};

format.date.add = function (timeSpan){return(timeSpan===null)?this:this.addSeconds(timeSpan.getTotalMilliseconds()/1000);};

format.date.subtract = function (timeSpan){return(timeSpan===null)?this:this.addSeconds(-timeSpan.getTotalMilliseconds()/1000);};

format.date.addDays = function (n){return new exports.TimeSpan(this.getTotalMilliseconds()+(n*24*60*60*1000));};

format.date.addHours = function (n){return new exports.TimeSpan(this.getTotalMilliseconds()+(n*60*60*1000));};

format.date.addMinutes = function (n){return new exports.TimeSpan(this.getTotalMilliseconds()+(n*60*1000));};

format.date.addSeconds = function (n){return new exports.TimeSpan(this.getTotalMilliseconds()+(n*1000));};

format.date.addMilliseconds = function (n){return new exports.TimeSpan(this.getTotalMilliseconds()+n);};

format.date.getTotalMilliseconds = function (){return(this.days()*(24*60*60*1000))+(this.hours()*(60*60*1000))+(this.minutes()*(60*1000))+(this.seconds()*(1000));};

format.date.get12HourHour = function (){return((h=this.hours()%12)?h:12);};

format.date.getDesignator = function (){return(this.hours()<12)?Date.CultureInfo.amDesignator:Date.CultureInfo.pmDesignator;};

format.date.toString = function (format){function _toString(){if(this.days()!==null&&this.days()>0){return this.days()+"."+this.hours()+":"+p(this.minutes())+":"+p(this.seconds());}
  else{return this.hours()+":"+p(this.minutes())+":"+p(this.seconds());}}
  function p(s){return(s.toString().length<2)?"0"+s:s;}
  var self=this;return format?format.replace(/d|dd|HH|H|hh|h|mm|m|ss|s|tt|t/g,function(format){switch(format){case"d":return self.days();case"dd":return p(self.days());case"H":return self.hours();case"HH":return p(self.hours());case"h":return self.get12HourHour();case"hh":return p(self.get12HourHour());case"m":return self.minutes();case"mm":return p(self.minutes());case"s":return self.seconds();case"ss":return p(self.seconds());case"t":return((this.hours()<12)?Date.CultureInfo.amDesignator:Date.CultureInfo.pmDesignator).substring(0,1);case"tt":return(this.hours()<12)?Date.CultureInfo.amDesignator:Date.CultureInfo.pmDesignator;}}):this._toString();};

format.currency = {};
format.currency.toDollars = function (money){
  // TODO: add more stripping and formatting logic
  return money;
};

format.currency.toPennies = function (money){
    // TODO: add more stripping and formatting logic
    return money;
  };

format.currency.toNickels = function (money){
    // TODO: add more stripping and formatting logic
    return money;
  };

format.currency.toDimes = function (money){
    // TODO: add more stripping and formatting logic
    return money;
  };

format.currency.toQuarters = function (money){
    // TODO: add more stripping and formatting logic
    return money;
  };

format.currency.toEuros = function (money){
  // TODO: add more stripping and formatting logic
  return money;
};

format.currency.toCanadian = function (money){
  // TODO: add more stripping and formatting logic
  return money;
};
if(typeof exports != "undefined"){for(var prop in format){exports[prop] = format[prop];}}